name: Build Standalone App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Allow other jobs to continue if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11]

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64  # Ensure compatibility for macOS

    # Step 3: Install Missing macOS Dependencies
    - name: macOS Dependency Fix
      if: runner.os == 'macOS'
      run: |
        brew install gettext  # Install the missing library
        brew link --force gettext

    # Step 4: Install Dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # Step 5: Build Application
    - name: Build Application
      run: |
        pyinstaller --onefile -n pathDB-Data-Retriever pathDB-Data-Retriever/downloader.py
      shell: bash

    # Step 6: Upload Artifacts
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pathDB-Data-Retriever-${{ matrix.os }}-${{ matrix.python-version }}
        path: dist/pathDB-Data-Retriever*
