name: Build Standalone App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Allow other matrix jobs to continue if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.10, 3.9]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Application
      run: |
        pyinstaller --onefile pathology-downloader.py
      shell: bash

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pathology-downloader-${{ matrix.os }}
        path: dist/pathology-downloader*

