name: Release Standalone App
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Standalone App"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        workflow: build.yml
        path: artifacts/

    - name: Extract Version from setup.py
      run: |
        echo "VERSION=$(python setup.py --version)" >> $GITHUB_ENV

    - name: Prepare Release Assets
      run: |
        mkdir release_assets
        for os in windows-latest macos-latest ubuntu-latest; do
          if [ "$os" == "windows-latest" ]; then
            ext=".exe"
          else
            ext=""
          fi

          # Find the executable for each OS
          executable=$(find artifacts -name "*$os*" -name "*pathDB-Data-Retriever$ext")

          if [ -n "$executable" ]; then
            # Compress the executable
            zip "release_assets/pathDB-Data-Retriever-$os-v${{ env.VERSION }}.zip" "$executable"
          fi
        done

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release v${{ env.VERSION }}
        body: |
          Automated release of pathDB-Data-Retriever
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release_assets/pathDB-Data-Retriever-windows-latest-v${{ env.VERSION }}.zip
        asset_name: pathDB-Data-Retriever-windows-latest-v${{ env.VERSION }}.zip
        asset_content_type: application/zip
      continue-on-error: true

    - name: Upload macOS Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release_assets/pathDB-Data-Retriever-macos-latest-v${{ env.VERSION }}.zip
        asset_name: pathDB-Data-Retriever-macos-latest-v${{ env.VERSION }}.zip
        asset_content_type: application/zip
      continue-on-error: true

    - name: Upload Ubuntu Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release_assets/pathDB-Data-Retriever-ubuntu-latest-v${{ env.VERSION }}.zip
        asset_name: pathDB-Data-Retriever-ubuntu-latest-v${{ env.VERSION }}.zip
        asset_content_type: application/zip
      continue-on-error: true
