name: Release Standalone App
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Standalone App"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: ${{ github.event.workflow_run.id }}
          });

          const fs = require('fs');
          const path = require('path');

          if (!fs.existsSync('artifacts')) {
            fs.mkdirSync('artifacts');
          }

          for (const artifact of artifacts.data.artifacts) {
            console.log(`Downloading artifact: ${artifact.name}`);
            const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: artifact.id,
              archive_format: 'zip'
            });

            fs.writeFileSync(path.join('artifacts', `${artifact.name}.zip`), Buffer.from(download.data));
          }

    - name: Extract and Unzip Artifacts
      run: |
        mkdir -p release_assets
        cd artifacts
        for zipfile in *.zip; do
          unzip "$zipfile" -d ../release_assets
        done
        cd ..

    - name: Extract Version from setup.py
      run: |
        echo "VERSION=$(python setup.py --version)" >> $GITHUB_ENV

    - name: Prepare Release Assets
      run: |
        for os in windows-latest macos-latest ubuntu-latest; do
          if [ "$os" == "windows-latest" ]; then
            ext=".exe"
          else
            ext=""
          fi

          # Find the executable for each OS
          executable=$(find release_assets -name "*$os*" -name "*pathDB-Data-Retriever$ext")

          if [ -n "$executable" ]; then
            # Zip the executable
            zip "pathDB-Data-Retriever-$os-v${{ env.VERSION }}.zip" "$executable"
          fi
        done

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release v${{ env.VERSION }}
        body: |
          Automated release of pathDB-Data-Retriever
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pathDB-Data-Retriever-windows-latest-v${{ env.VERSION }}.zip
        asset_name: pathDB-Data-Retriever-windows-latest-v${{ env.VERSION }}.zip
        asset_content_type: application/zip
      continue-on-error: true

    - name: Upload macOS Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pathDB-Data-Retriever-macos-latest-v${{ env.VERSION }}.zip
        asset_name: pathDB-Data-Retriever-macos-latest-v${{ env.VERSION }}.zip
        asset_content_type: application/zip
      continue-on-error: true

    - name: Upload Ubuntu Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pathDB-Data-Retriever-ubuntu-latest-v${{ env.VERSION }}.zip
        asset_name: pathDB-Data-Retriever-ubuntu-latest-v${{ env.VERSION }}.zip
        asset_content_type: application/zip
      continue-on-error: true
